//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oblasti
    {
        public Oblasti()
        {
            this.Ulice = new HashSet<Ulice>();
        }
    
        public int Id { get; set; }
        public int Id_Grada { get; set; }
        public string Name { get; set; }
        public string Zona1 { get; set; }
        public string Zona2 { get; set; }
        public string Zona3 { get; set; }
    
        public virtual Gradovi Gradovi { get; set; }
        public virtual ICollection<Ulice> Ulice { get; set; }
    }
}
