//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacije
    {
        public int ID { get; set; }
        public int KorisniciID { get; set; }
        public System.DateTime DatumVreme { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<System.DateTime> ConfrimDateTime { get; set; }
        public string FromToAirport { get; set; }
        public string CarType { get; set; }
        public Nullable<int> Suitcases { get; set; }
        public string Payment { get; set; }
        public double Price { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
    }
}
