resourcesG = {
    email: "Ihre E-Mail",
    plhemail: "Geben Sie E-Mail",
    fullname: "Name",
    plhfullname: "Geben Sie den Namen",
    pickupdate: "Abholdatum",
    plhpickupdate: "Geben Sie Datum",
    pickupHRS: "Abholen Stunden",
    house: "Hausnummer",
    floor: "Fußboden",
    door: "Tür",
    pickupfrom: "Abholung",
    from1: "von zu Hause aus",
    from2: "aus dem Amt",
    from3: "von der Zugstation",
    from4: "vom Hotel",
    location: "Lage",
    street: "Straße",
    phone: "Telefon",
    plhphone: "Geben Sie Ihre Telefon",
    cartype: "Fahrzeugtyp",
    car1: "Economy klase (bis 4 personen)",
    car2: "Business klase (bis 4 personen)",
    car3: "Großram taxi (5 bis 8 personen)",
    suitcase: "Koffer",
    suit1: "Kaine Koffer",
    suit2: "1 Koffer",
    suit3: "2 Koffer",
    suit4: "3 Koffer",
    suit5: "4 Koffer",
    suit6: "5 Koffer",
    suit7: "6 Koffer",
    suit8: "7 Koffer",
    suit9: "8 Koffer",
    suit10: "Mehr von 8 auf Anfrage",
    hand: "Handgepäck",
    hand1: "Kein Handgepäck",
    hand2: "1 Stück",
    hand3: "2 Stück",
    hand4: "3 Stück",
    hand5: "4 Stück",
    hand6: "5 Stück",
    hand7: "6 Stück",
    hand8: "7 Stück",
    hand9: "8 Stück",
    hand10: "Mehr von 8 auf Anfrage",
    payment: "Bezahlung",
    pay1: "Bargeld",
    pay2: "Kreditkarte",
    pay3: "Banküberweisung",
    comment: "Kommentar",
    price: "Preis",
    lblreturn: "Hin- und Rückfahrt",
    title: "Buchung Zum Flughafen&nbsp<i class='fa fa-plane'></i>",
    see: "Sehen die Preise",
    home: "Start Seite",
    about: "Über uns",
    booking: "Reservierung",
    toairport: "Buchen Sie zum Flughafen&nbsp<i class='fa fa-plane'></i>",
    fromairport: "Buchung vom Flughafen&nbsp<i class='fa fa-plane fa-rotate-180'></i>",
    contact: "Kontakt",
    text: "Transfer vom und zum Flughafen <br/> <ul><li>24 h Service</li> <li>Fixpreise ab 25 €</li> <li>zuverlässig, sicher und schnell</li> <li>freundliche und kompetente Lenker</li> <li>Economy, Business und Großraumtaxi</li><li> österreichweit</li></ul>",
    aboutnaslov1: "<u>Wir sind die Besten im Business</u>",
    aboutnaslov2: "Beste Online-Reservierung sistyem ...",
    aboutsadrzaj1: "Unsere Unternehmensphilosophie ist stark auf die Ansprüche unserer Kunden ausgerichtet. Sie können sicher sein, dass Sie ein freundlicher, hilfsbereiter und erfahrener Lenker erwartet, sowie ein sauberes, modernes Auto, das alle Annehmlichkeiten und besten Komfort  für eine angenehme Fahrt bietet.",
    aboutnaslov3: "<u>Vorbestellen</u>",
    aboutsadrzaj2: "Bestellen Sie einfach und bequem Ihr Flughafentaxi im Voraus und kommen Sie entspannt am Flughafen Wien an, mit der Gewissheit, dass schon ein Wagen für Sie bereit steht.",
    aboutnaslov4: "<u>Sichere Online-Reservierung</u>",
    aboutsadrzaj3: "Unser sicheres Onlinebestellsystem wurde entwickelt um sicherzustellen, dass die Daten von unseren Kunden vollständig geschützt bleiben. Sie erhalten eine sofortige Buchungsbestätigung für Ihre Online-Reservierung.",
    surname: "Geben Sie Ihren Nachnamen",
    message: "Geben Sie Ihre Massage für uns hier. Wir werden uns umgehend mit Ihnen innerhalb von 2 Tagen.",
    contacttitle: "Kontaktieren Sie uns",
    flightfrom: "Flug ab",
    flightnumber: "Flugnummer"   
}

resources = {
    email: "Your email",
    plhemail: "Enter email",
    fullname: "Name",
    plhfullname: "Enter your name",
    pickupdate: "Pick up date",
    plhpickupdate: "enter date",
    pickupHRS: "Pick up time",
    house: "House",
    floor: "Floor",
    door: "door",
    pickupfrom: "Pick up from",
    from1: "from House",
    from2: "from office",
    from3: "from train station",
    from4: "from hotel",
    location: "Location",
    street: "Street",
    phone: "Phone",
    plhphone: "Enter phone number",
    cartype: "Car type",
    car1: "Economy class (4 person max)",
    car2: "Business klase (4 person max)",
    car3: "Großram taxi (5 to 8 person)",
    suitcase: "Suitcase",
    suit1: "No Suitcase",
    suit2: "1 Suitcase",
    suit3: "2 Suitcase",
    suit4: "3 Suitcase",
    suit5: "4 Suitcase",
    suit6: "5 Suitcase",
    suit7: "6 Suitcase",
    suit8: "7 Suitcase",
    suit9: "8 Suitcase",
    suit10: "More than 8 on request",
    hand: "Hand laguage",
    hand1: "No laguage",
    hand2: "1 Laguage",
    hand3: "2 Laguage",
    hand4: "3 Laguage",
    hand5: "4 Laguage",
    hand6: "5 Laguage",
    hand7: "6 Laguage",
    hand8: "7 Laguage",
    hand9: "8 Stück",
    hand10: "More than 8 on request",
    payment: "Payment",
    pay1: "Cash",
    pay2: "Credit card",
    pay3: "Bank transfer",
    comment: "Comment",
    price: "Price",
    lblreturn: "Return trip",
    title: "Booking to Airport&nbsp<i class='fa fa-plane'></i>",
    see: "See the prices",
    home: "Home",
    about: "About",
    booking: "Booking",
    toairport: "Booking to the Airport&nbsp<i class='fa fa-plane'></i>",
    fromairport: "Booking from the Airport&nbsp<i class='fa fa-plane fa-rotate-180'></i>",
    contact: "Contact",
    text: "Transfer from and to the airport <br/> <ul> <li> 24-hour service </ li> <li> fixed prices from 25 € </ li> <li> reliable, safe and fast </ li> <li> friendly and competent link </ li> <li> Economy, Business and Large Taxi </ li> <li> throughout Austria </ li> </ ul>",
    aboutnaslov1: "<u>We are the Best in the Business!</u>",
    aboutnaslov2: "Best online reservation sistyem...",
    aboutsadrzaj1: "Our company philosophy is strongly focused on the needs of our customers. You can be sure that you will find a friendly, helpful and experienced handlebars, and a clean, modern car that offers all the amenities and comfort for a pleasant ride.",
    aboutnaslov3: "<u>Order in Advance</u>",
    aboutsadrzaj2: "Order easy and convenient, your airport taxi in advance and come relax at Vienna International Airport on, with the certainty that even a car is ready for you.",
    aboutnaslov4: "<u>Secure Online Reservations</u>",
    aboutsadrzaj3: "Our secure online ordering system was developed that the data is completely protected for our customers to be sure about information safety. You will receive an instant confirmation for your online booking.",
    surname: "Enter your surname",
    message: "Enter your massage for us here. We will get back to you within 2 business days.",
    contacttitle: "Contact us",
    flightfrom: "Flight from",
    flightnumber: "Flight number"

}
