resourcesG = {
    email: "Ihre E-Mail",
    plhemail: "Geben Sie E-Mail",
    fullname: "Name",
    plhfullname: "Geben Sie den Namen",
    pickupdate: "Abholdatum",
    plhpickupdate: "Geben Sie Datum",
    pickupHRS: "Abholen Stunden",
    house: "Haus",
    floor: "Fußboden",
    door: "Tür",
    pickupfrom: "Abholung",
    from1: "von zu Hause aus",
    from2: "aus dem Amt",
    from3: "von der Zugstation",
    from4: "vom Hotel",
    location: "Lage",
    street: "Straße",
    phone: "Telefon",
    plhphone: "Geben Sie Ihre Telefon",
    cartype: "Fahrzeugtyp",
    car1: "Economy klase (bis 4 personen)",
    car2: "Business klase (bis 4 personen)",
    car3: "Großram taxi (5 bis 8 personen)",
    suitcase: "Koffer",
    suit1: "Kaine Koffer",
    suit2: "1 Koffer",
    suit3: "2 Koffer",
    suit4: "3 Koffer",
    suit5: "4 Koffer",
    suit6: "5 Koffer",
    suit7: "6 Koffer",
    suit8: "7 Koffer",
    suit9: "8 Koffer",
    suit10: "Mehr von 8 auf Anfrage",
    hand: "Handgepäck",
    hand1: "Kein Handgepäck",
    hand2: "1 Stück",
    hand3: "2 Stück",
    hand4: "3 Stück",
    hand5: "4 Stück",
    hand6: "5 Stück",
    hand7: "6 Stück",
    hand8: "7 Stück",
    hand9: "8 Stück",
    hand10: "Mehr von 8 auf Anfrage",
    payment: "Bezahlung",
    pay1: "Bargeld",
    pay2: "Kreditkarte",
    pay3: "Banküberweisung",
    comment: "Kommentar",
    price: "Preis",
    lblreturn: "Hin- und Rückfahrt",
    title: "Buchung Zum Flughafen&nbsp<i class='fa fa-plane'></i>",
    see: "Sehen die Preise",
    home: "Zuhause",
    about: "Über uns",
    booking: "Reservierung",
    toairport: "Buchen Sie zum Flughafen&nbsp<i class='fa fa-plane'></i>",
    fromairport: "Buchung vom Flughafen&nbsp<i class='fa fa-plane fa-rotate-180'></i>",
    contact: "Kontakt",
    text: "Flughafen-Taxi Taxi-Service bietet viele Dienstleistungen, die Ihre Transportbedürfnisse in Vienn einfacher und billiger machen wird. Eine zuverlässige 24 h Taxiservice - schnell, sicher und effizient von Tür zu Tür-Taxi-Service, wettbewerbsfähige Preise, erfahren, kompetent, unterhaltsam und Englisch sprechenden Fahrer, klimatisierte Fahrzeuge, die alle Ihre Transport-Bedürfnisse in Vienn ... Flughafenservice - Flughafen Pick ups und Drop-offs, Main-Flughafen wir dienen Flughafentransfers Österreich, sondern kann von jedem Ort in Österreich hergestellt werden, Überweisungen für Ihre Bequemlichkeit und geschäftlichen Verpflichtungen, klimatisierten Transfer Fahrzeuge ...",
    aboutnaslov1: "Wir sind die Besten im Business!",
    aboutnaslov2: "Beste Online-Reservierung sistyem ...",
    aboutsadrzaj1: "Es ist Zeit, über eine andere Art, die Dinge zu denken. Während Sie vielleicht nicht in der Lage, irgendetwas über bestimmte Aspekte von Luft Reise zu tun, können Sie etwas über die Bodentransport part.Our Unternehmen ist auf die Bereitstellung qualitativ hochwertiger Flughafen Taxi-Service konzentriert zu tun. Sie können sicher sein, dass Sie eine höfliche Fahrer bereit, Sie in irgendeiner Weise zu helfen, aber auch ein sauberes, modernes Auto, das alle Annehmlichkeiten bietet und Komfort, den Sie brauchen, um Ihre Fahrt so angenehm wie möglich zu haben.",
    aboutnaslov3: "Vorbestellen",
    aboutsadrzaj2: "Wenn Sie bestellen Flughafen-Taxi im Voraus, können Sie am Flughafen Wien in dem sicheren Wissen, dass ein Auto und Fahrer wird es warten auf Sie kommen. Es ist nicht notwendig, um in der Schlange stehen, sondern einfach an Ihr Gepäck und den Kopf aus dem Wagen, der wartet.",
    aboutnaslov4: "Sichere Online-Reservierungen",
    aboutsadrzaj3: "Unser sicheres Onlinebestellsystem wurde entwickelt, um sicherzustellen, dass Passagiere Online-Informationen ist vollständig geschützt. Sie erhalten eine sofortige Buchungsbestätigung für Ihre für Ihre Buchungen zu erhalten.",
    surname: "Geben Sie Ihren Nachnamen",
    message: "Geben Sie Ihre Massage für uns hier. Wir werden uns umgehend mit Ihnen innerhalb von 2 Tagen.",
    contacttitle: "Kontaktieren Sie uns",
    flightfrom: "Flug ab",
    flightnumber: "Flugnummer"
    
}

resources = {
    email: "Your email",
    plhemail: "Enter email",
    fullname: "Name",
    plhfullname: "Enter your name",
    pickupdate: "Pick up date",
    plhpickupdate: "enter date",
    pickupHRS: "Pick up time",
    house: "House",
    floor: "Floor",
    door: "door",
    pickupfrom: "Pick up from",
    from1: "from House",
    from2: "from office",
    from3: "from train station",
    from4: "from hotel",
    location: "Location",
    street: "Street",
    phone: "Phone",
    plhphone: "Enter phone number",
    cartype: "Car type",
    car1: "Economy class (4 person max)",
    car2: "Business klase (4 person max)",
    car3: "Großram taxi (5 to 8 person)",
    suitcase: "Suitcase",
    suit1: "No Suitcase",
    suit2: "1 Suitcase",
    suit3: "2 Suitcase",
    suit4: "3 Suitcase",
    suit5: "4 Suitcase",
    suit6: "5 Suitcase",
    suit7: "6 Suitcase",
    suit8: "7 Suitcase",
    suit9: "8 Suitcase",
    suit10: "More than 8 on request",
    hand: "Hand laguage",
    hand1: "No laguage",
    hand2: "1 Laguage",
    hand3: "2 Laguage",
    hand4: "3 Laguage",
    hand5: "4 Laguage",
    hand6: "5 Laguage",
    hand7: "6 Laguage",
    hand8: "7 Laguage",
    hand9: "8 Stück",
    hand10: "More than 8 on request",
    payment: "Payment",
    pay1: "Cash",
    pay2: "Credit card",
    pay3: "Bank transfer",
    comment: "Comment",
    price: "Price",
    lblreturn: "Return trip",
    title: "Booking to Airport&nbsp<i class='fa fa-plane'></i>",
    see: "See the prices",
    home: "Home",
    about: "About",
    booking: "Booking",
    toairport: "Booking to the Airport&nbsp<i class='fa fa-plane'></i>",
    fromairport: "Booking from the Airport&nbsp<i class='fa fa-plane fa-rotate-180'></i>",
    contact: "Contact",
    text: "Flughafen-Taxi taxi service provides many services that will make your transportation needs in Vienn easier and cheaper. A  reliable  24  hour  taxi  service   -   fast,  secure  and  efficient  door-to-door  taxi service, competitive rates, experienced, knowledgeable, entertaining and English speaking drivers,  air-conditioned   vehicles,  all   your   transportation  needs  in Vienn... Airport  service  -  Airport  pick  ups  and  drop  offs,  Main  airport  we  serve  is Austria airport but transfers can be made from any town in Austria, transfers for your convenience and business commitments, air conditioned transfer vehicles... ",
    aboutnaslov1: "We are the Best in the Business!",
    aboutnaslov2: "Best online reservation sistyem...",
    aboutsadrzaj1: "It’s time to think about a different way of doing things. While You may not be able to do anything about certain aspects of air travel, You can do something about the ground transportation part.Our company is focused on providing high-quality airport taxi service. You can be sure that You will have a courteous driver willing to help You in any way they can, as well as a clean, modern car that features all of the amenities and comforts You need to make Your ride a pleasurable one.",
    aboutnaslov3: "Order in Advance",
    aboutsadrzaj2: "When You order airport taxi in advance, You can arrive at Vienna Airport safe in the knowledge that a car and driver will be there waiting for You. There is no need to stand in line, but rather just grab your luggage and head out to the car that awaits.",
    aboutnaslov4: "Secure Online Reservations",
    aboutsadrzaj3: "Our secure booking system is designed to make sure that passengers online information is fully protected. You will receive an instant confirmation for Your for Your bookings.",
    surname: "Enter your surname",
    message: "Enter your massage for us here. We will get back to you within 2 business days.",
    contacttitle: "Contact us",
    flightfrom: "Flight from",
    flightnumber: "Flight number"

}
